name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build on Ubuntu
        if: runner.os == 'Linux'
        run: make

      # - name: Setup Build Environment on Windows
      #   if: runner.os == 'Windows'
      #   uses: microsoft/setup-msbuild@v1
      #   with:
      #     msbuild-version: 'latest'

      # - name: Build on Windows with MSBuild
      #   if: runner.os == 'Windows'
      #   run: |
      #     msbuild teapot.sln /p:Configuration=Release /p:Platform="x64" /p:CXXStandard=20 /p:LanguageStandard=C++20

  test:
    runs-on: ubuntu-latest # Or another suitable OS
    needs: build # Run the test after the build job
    steps:
      - uses: actions/checkout@v3
      - name: Run endpoint tests
        run: bash ./teapot 8888 && ./tests/e2e_tests.sh
