name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build on Ubuntu
        if: runner.os == 'Linux'
        run: make

      - name: Setup Build Environment on Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set C++ Standard to C++20 in Project Files
        if: runner.os == 'Windows'
        run: |
          Get-Content teapot.vcxproj | Foreach-Object { $_ -replace '<LanguageStandard>stdcpplatest</LanguageStandard>', '<LanguageStandard>stdcpp20</LanguageStandard>' } | Set-Content teapot.vcxproj
        shell: pwsh

      - name: Build on Windows with MSBuild
        if: runner.os == 'Windows'
        run: |
          msbuild teapot.sln /p:Configuration=Release /p:Platform="x64"

